import { BASE_COMMANDS } from "./command-library.js";

const CRYSTAL = 0xffc857;
const BLUE = 0x5ca9ff;
const GREEN = 0x64e06b;
const CYAN = 0x17d6c3;
const RED = 0xff6b6b;

function allow(...keys) {
    return [...BASE_COMMANDS, ...keys];
}

export const LEVELS = [
    {
        id: "floor-01",
        name: "Boot Line",
        introduces: "MoveForward()",
        grid: 5,
        start: { x: 2, y: 4, dir: 0 },
        exit: { x: 2, y: 1 },
        chips: [{ x: 2, y: 3 }, { x: 2, y: 2 }, { x: 2, y: 1 }],
        obstacles: [],
        switches: [],
        doors: [],
        bridges: [],
        guards: [],
        lasers: [],
        requiredPower: [],
        allowed: allow(),
        stars: { three: 3, two: 4, one: 5 },
        mission: "Collect the data trail and reach the gate.",
        template: "MoveForward();\nMoveForward();\nMoveForward();"
    },
    {
        id: "floor-02",
        name: "Right Angle",
        introduces: "TurnRight()",
        grid: 6,
        start: { x: 1, y: 4, dir: 0 },
        exit: { x: 4, y: 3 },
        chips: [{ x: 1, y: 3 }, { x: 2, y: 3 }, { x: 3, y: 3 }, { x: 4, y: 3 }],
        obstacles: [],
        switches: [],
        doors: [],
        bridges: [],
        guards: [],
        lasers: [],
        requiredPower: [],
        allowed: allow(),
        stars: { three: 5, two: 7, one: 9 },
        mission: "Turn once, then cross the row cleanly.",
        template: "MoveForward();\nTurnRight();\nMoveForward();\nMoveForward();\nMoveForward();"
    },
    {
        id: "floor-03",
        name: "Left Hook",
        introduces: "TurnLeft()",
        grid: 6,
        start: { x: 4, y: 4, dir: 3 },
        exit: { x: 1, y: 1 },
        chips: [{ x: 3, y: 4 }, { x: 2, y: 4 }, { x: 2, y: 2 }, { x: 1, y: 1 }],
        obstacles: [{ x: 3, y: 3 }, { x: 4, y: 2 }],
        switches: [],
        doors: [],
        bridges: [],
        guards: [],
        lasers: [],
        requiredPower: [],
        allowed: allow(),
        stars: { three: 9, two: 11, one: 13 },
        mission: "Use both turns to bend around blocked platforms.",
        template: "MoveForward();\nMoveForward();\nTurnRight();\nMoveForward();\nMoveForward();\nTurnLeft();\nMoveForward();\nTurnRight();\nMoveForward();"
    },
    {
        id: "floor-04",
        name: "Loop Hall",
        introduces: "Repeat()",
        grid: 7,
        start: { x: 1, y: 5, dir: 0 },
        exit: { x: 5, y: 3 },
        chips: [{ x: 1, y: 4 }, { x: 1, y: 3 }, { x: 3, y: 3 }, { x: 5, y: 3 }],
        obstacles: [{ x: 2, y: 4 }, { x: 4, y: 4 }],
        switches: [],
        doors: [],
        bridges: [],
        guards: [],
        lasers: [],
        requiredPower: [],
        allowed: allow("Repeat"),
        stars: { three: 7, two: 9, one: 12 },
        mission: "Compress repeated movement into a loop.",
        template: "Repeat(2, function() {\n  MoveForward();\n});\nTurnRight();\nRepeat(4, function() {\n  MoveForward();\n});"
    },
    {
        id: "floor-05",
        name: "First Circuit",
        introduces: "Use()",
        grid: 6,
        start: { x: 1, y: 4, dir: 0 },
        exit: { x: 4, y: 3 },
        chips: [{ x: 1, y: 3 }, { x: 2, y: 3 }, { x: 4, y: 3 }],
        obstacles: [{ x: 2, y: 2 }],
        switches: [{ x: 1, y: 3, power: "A", mode: "on", color: CYAN }],
        doors: [{ x: 3, y: 3, requires: ["A"], color: CYAN }],
        bridges: [],
        guards: [],
        lasers: [],
        requiredPower: ["A"],
        allowed: allow("Repeat", "Use"),
        stars: { three: 6, two: 8, one: 10 },
        mission: "Turn the electricity on before crossing the locked gate.",
        template: "MoveForward();\nUse();\nTurnRight();\nMoveForward();\nMoveForward();\nMoveForward();"
    },
    {
        id: "floor-06",
        name: "Dual Current",
        introduces: "Use()",
        grid: 8,
        start: { x: 1, y: 5, dir: 0 },
        exit: { x: 6, y: 4 },
        chips: [{ x: 1, y: 4 }, { x: 3, y: 4 }, { x: 6, y: 4 }],
        obstacles: [{ x: 2, y: 5 }, { x: 4, y: 3 }],
        switches: [
            { x: 1, y: 4, power: "A", mode: "on", color: CYAN },
            { x: 3, y: 4, power: "B", mode: "on", color: GREEN }
        ],
        doors: [{ x: 5, y: 4, requires: ["A", "B"], color: GREEN }],
        bridges: [],
        guards: [],
        lasers: [],
        requiredPower: ["A", "B"],
        allowed: allow("Repeat", "Use"),
        stars: { three: 9, two: 12, one: 15 },
        mission: "Two circuits are required before the heavy door opens.",
        template: "MoveForward();\nUse();\nTurnRight();\nRepeat(2, function() {\n  MoveForward();\n});\nUse();\nRepeat(3, function() {\n  MoveForward();\n});"
    },
    {
        id: "floor-07",
        name: "Bridge Power",
        introduces: "Use()",
        grid: 7,
        start: { x: 1, y: 5, dir: 0 },
        exit: { x: 4, y: 4 },
        chips: [{ x: 1, y: 4 }, { x: 3, y: 4 }, { x: 4, y: 4 }],
        obstacles: [{ x: 2, y: 3 }, { x: 5, y: 4 }],
        switches: [{ x: 1, y: 4, power: "A", mode: "on", color: BLUE }],
        doors: [],
        bridges: [{ cells: [{ x: 2, y: 4 }, { x: 3, y: 4 }], requires: ["A"], color: BLUE }],
        guards: [],
        lasers: [],
        requiredPower: ["A"],
        allowed: allow("Repeat", "Use"),
        stars: { three: 6, two: 8, one: 10 },
        mission: "Bring the bridge online before stepping onto it.",
        template: "MoveForward();\nUse();\nTurnRight();\nRepeat(3, function() {\n  MoveForward();\n});"
    },
    {
        id: "floor-08",
        name: "Clock Guard",
        introduces: "Wait()",
        grid: 6,
        start: { x: 1, y: 4, dir: 1 },
        exit: { x: 4, y: 4 },
        chips: [{ x: 2, y: 4 }, { x: 4, y: 4 }],
        obstacles: [{ x: 3, y: 2 }],
        switches: [],
        doors: [],
        bridges: [],
        guards: [{ name: "Sentry", color: BLUE, path: [{ x: 2, y: 4 }, { x: 2, y: 3 }, { x: 3, y: 3 }, { x: 2, y: 3 }], phase: 0, vision: 0 }],
        lasers: [],
        requiredPower: [],
        allowed: allow("Repeat", "Use", "Wait"),
        stars: { three: 4, two: 6, one: 9 },
        mission: "The guard follows a fixed clock. Let it move first.",
        template: "Wait();\nMoveForward();\nMoveForward();\nMoveForward();"
    },
    {
        id: "floor-09",
        name: "Patrol Window",
        introduces: "Wait()",
        grid: 7,
        start: { x: 1, y: 5, dir: 0 },
        exit: { x: 5, y: 3 },
        chips: [{ x: 1, y: 4 }, { x: 3, y: 4 }, { x: 5, y: 4 }, { x: 5, y: 3 }],
        obstacles: [{ x: 2, y: 3 }, { x: 4, y: 5 }],
        switches: [],
        doors: [],
        bridges: [],
        guards: [{ name: "Meter", color: RED, path: [{ x: 3, y: 4 }, { x: 3, y: 3 }, { x: 4, y: 3 }, { x: 3, y: 3 }], phase: 0, vision: 0 }],
        lasers: [],
        requiredPower: [],
        allowed: allow("Repeat", "Use", "Wait"),
        stars: { three: 10, two: 13, one: 16 },
        mission: "Wait for the repeating patrol window, then cross.",
        template: "MoveForward();\nTurnRight();\nMoveForward();\nWait();\nWait();\nRepeat(3, function() {\n  MoveForward();\n});\nTurnLeft();\nMoveForward();"
    },
    {
        id: "floor-10",
        name: "Power Under Patrol",
        introduces: "Wait()",
        grid: 7,
        start: { x: 1, y: 5, dir: 0 },
        exit: { x: 5, y: 4 },
        chips: [{ x: 1, y: 4 }, { x: 4, y: 4 }, { x: 5, y: 4 }],
        obstacles: [{ x: 3, y: 3 }, { x: 5, y: 5 }],
        switches: [{ x: 1, y: 4, power: "A", mode: "on", color: CYAN }],
        doors: [{ x: 4, y: 4, requires: ["A"], color: CYAN }],
        bridges: [],
        guards: [{ name: "Gatebot", color: CRYSTAL, path: [{ x: 2, y: 4 }, { x: 2, y: 3 }, { x: 3, y: 3 }, { x: 2, y: 3 }], phase: 0, vision: 0 }],
        lasers: [],
        requiredPower: ["A"],
        allowed: allow("Repeat", "Use", "Wait"),
        stars: { three: 9, two: 12, one: 15 },
        mission: "Power the door, then wait out the patrol before moving.",
        template: "MoveForward();\nUse();\nTurnRight();\nWait();\nWait();\nRepeat(4, function() {\n  MoveForward();\n});"
    },
    {
        id: "floor-11",
        name: "Laser Timing",
        introduces: "Wait()",
        grid: 7,
        start: { x: 1, y: 4, dir: 1 },
        exit: { x: 5, y: 4 },
        chips: [{ x: 2, y: 4 }, { x: 5, y: 4 }],
        obstacles: [{ x: 3, y: 3 }, { x: 4, y: 5 }],
        switches: [],
        doors: [],
        bridges: [],
        guards: [],
        lasers: [{ cells: [{ x: 3, y: 4 }], period: 5, active: [0, 1], color: RED }],
        requiredPower: [],
        allowed: allow("Repeat", "Use", "Wait"),
        stars: { three: 5, two: 7, one: 10 },
        mission: "Cross the laser only while its cycle is dark.",
        template: "MoveForward();\nWait();\nMoveForward();\nMoveForward();\nMoveForward();"
    },
    {
        id: "floor-12",
        name: "Powered Branch",
        introduces: "IfPowerOn()",
        grid: 6,
        start: { x: 1, y: 4, dir: 0 },
        exit: { x: 4, y: 3 },
        chips: [{ x: 1, y: 3 }, { x: 4, y: 3 }],
        obstacles: [{ x: 2, y: 2 }],
        switches: [{ x: 1, y: 3, power: "A", mode: "on", color: GREEN }],
        doors: [{ x: 3, y: 3, requires: ["A"], color: GREEN }],
        bridges: [],
        guards: [],
        lasers: [],
        requiredPower: ["A"],
        allowed: allow("Repeat", "Use", "Wait", "IfPowerOn"),
        stars: { three: 6, two: 8, one: 11 },
        mission: "Only run the gate route once the circuit is live.",
        template: "MoveForward();\nUse();\nTurnRight();\nIfPowerOn(\"A\", function() {\n  Repeat(3, function() {\n    MoveForward();\n  });\n});"
    },
    {
        id: "floor-13",
        name: "Clear Check",
        introduces: "IfPathClear()",
        grid: 6,
        start: { x: 1, y: 4, dir: 1 },
        exit: { x: 4, y: 4 },
        chips: [{ x: 2, y: 4 }, { x: 3, y: 4 }, { x: 4, y: 4 }],
        obstacles: [{ x: 2, y: 3 }, { x: 5, y: 4 }],
        switches: [],
        doors: [],
        bridges: [],
        guards: [],
        lasers: [],
        requiredPower: [],
        allowed: allow("Repeat", "Use", "Wait", "IfPowerOn", "IfPathClear"),
        stars: { three: 3, two: 5, one: 8 },
        mission: "Use path checks to move only when the next tile is open.",
        template: "IfPathClear(function() {\n  MoveForward();\n});\nIfPathClear(function() {\n  MoveForward();\n});\nIfPathClear(function() {\n  MoveForward();\n});"
    },
    {
        id: "floor-14",
        name: "Clear Sweep",
        introduces: "WhilePathClear()",
        grid: 7,
        start: { x: 1, y: 2, dir: 1 },
        exit: { x: 5, y: 2 },
        chips: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 2 }, { x: 5, y: 2 }],
        obstacles: [{ x: 6, y: 2 }, { x: 3, y: 3 }],
        switches: [],
        doors: [],
        bridges: [],
        guards: [],
        lasers: [],
        requiredPower: [],
        allowed: allow("Repeat", "Use", "Wait", "IfPowerOn", "IfPathClear", "WhilePathClear"),
        stars: { three: 4, two: 6, one: 9 },
        mission: "Sweep forward until the route is blocked.",
        template: "WhilePathClear(function() {\n  MoveForward();\n});"
    },
    {
        id: "floor-15",
        name: "Return Current",
        introduces: "TurnAround()",
        grid: 7,
        start: { x: 3, y: 5, dir: 0 },
        exit: { x: 0, y: 5 },
        chips: [{ x: 3, y: 3 }, { x: 1, y: 5 }, { x: 0, y: 5 }],
        obstacles: [{ x: 2, y: 4 }, { x: 4, y: 4 }],
        switches: [{ x: 3, y: 3, power: "A", mode: "on", color: CYAN }],
        doors: [{ x: 1, y: 5, requires: ["A"], color: CYAN }],
        bridges: [],
        guards: [],
        lasers: [],
        requiredPower: ["A"],
        allowed: allow("Repeat", "Use", "Wait", "IfPowerOn", "IfPathClear", "WhilePathClear", "TurnAround"),
        stars: { three: 10, two: 13, one: 16 },
        mission: "Turn back from a powered dead end and unlock the lower gate.",
        template: "Repeat(2, function() {\n  MoveForward();\n});\nUse();\nTurnAround();\nRepeat(2, function() {\n  MoveForward();\n});\nTurnRight();\nRepeat(3, function() {\n  MoveForward();\n});"
    },
    {
        id: "floor-16",
        name: "Relay Bridge",
        introduces: "WhilePathClear()",
        grid: 8,
        start: { x: 1, y: 6, dir: 0 },
        exit: { x: 6, y: 5 },
        chips: [{ x: 1, y: 5 }, { x: 3, y: 5 }, { x: 6, y: 5 }],
        obstacles: [{ x: 7, y: 5 }, { x: 2, y: 4 }],
        switches: [{ x: 1, y: 5, power: "A", mode: "on", color: BLUE }],
        doors: [{ x: 6, y: 5, requires: ["A"], color: BLUE }],
        bridges: [{ cells: [{ x: 2, y: 5 }, { x: 3, y: 5 }, { x: 4, y: 5 }, { x: 5, y: 5 }], requires: ["A"], color: BLUE }],
        guards: [],
        lasers: [],
        requiredPower: ["A"],
        allowed: allow("Repeat", "Use", "Wait", "IfPowerOn", "IfPathClear", "WhilePathClear", "TurnAround"),
        stars: { three: 8, two: 11, one: 15 },
        mission: "Power the relay, then let the loop carry Nova to the door.",
        template: "MoveForward();\nUse();\nTurnRight();\nWhilePathClear(function() {\n  MoveForward();\n});"
    },
    {
        id: "floor-17",
        name: "Dark Bridge",
        introduces: "Wait()",
        grid: 8,
        start: { x: 1, y: 6, dir: 0 },
        exit: { x: 6, y: 5 },
        chips: [{ x: 1, y: 5 }, { x: 4, y: 5 }, { x: 6, y: 5 }],
        obstacles: [{ x: 7, y: 5 }],
        switches: [{ x: 1, y: 5, power: "A", mode: "on", color: GREEN }],
        doors: [],
        bridges: [{ cells: [{ x: 2, y: 5 }, { x: 3, y: 5 }, { x: 4, y: 5 }, { x: 5, y: 5 }, { x: 6, y: 5 }], requires: ["A"], color: GREEN }],
        guards: [],
        lasers: [{ cells: [{ x: 4, y: 5 }], period: 8, active: [5, 6], color: RED }],
        requiredPower: ["A"],
        allowed: allow("Repeat", "Use", "Wait", "IfPowerOn", "IfPathClear", "WhilePathClear", "TurnAround"),
        stars: { three: 10, two: 13, one: 17 },
        mission: "The bridge is powered, but the laser still keeps time.",
        template: "MoveForward();\nUse();\nTurnRight();\nRepeat(2, function() {\n  MoveForward();\n});\nWait();\nWait();\nRepeat(3, function() {\n  MoveForward();\n});"
    },
    {
        id: "floor-18",
        name: "Core Override",
        introduces: "All systems",
        grid: 9,
        start: { x: 1, y: 7, dir: 0 },
        exit: { x: 8, y: 4 },
        chips: [{ x: 1, y: 6 }, { x: 4, y: 5 }, { x: 5, y: 4 }, { x: 8, y: 4 }],
        obstacles: [{ x: 2, y: 7 }, { x: 3, y: 5 }, { x: 7, y: 5 }],
        switches: [
            { x: 1, y: 6, power: "A", mode: "on", color: BLUE },
            { x: 5, y: 4, power: "B", mode: "on", color: CYAN }
        ],
        doors: [{ x: 7, y: 4, requires: ["A", "B"], color: CYAN }],
        bridges: [{ cells: [{ x: 2, y: 6 }, { x: 3, y: 6 }, { x: 4, y: 6 }], requires: ["A"], color: BLUE }],
        guards: [{ name: "Core", color: RED, path: [{ x: 4, y: 5 }, { x: 5, y: 5 }, { x: 5, y: 6 }, { x: 5, y: 5 }], phase: 0, vision: 0 }],
        lasers: [{ cells: [{ x: 6, y: 4 }], period: 6, active: [0, 1, 2], color: RED }],
        requiredPower: ["A", "B"],
        allowed: allow("Repeat", "Use", "Wait", "IfPowerOn", "IfPathClear", "WhilePathClear", "TurnAround"),
        stars: { three: 18, two: 22, one: 28 },
        mission: "Power the bridge, dodge the patrol, time the laser, and open the final core.",
        template: "MoveForward();\nUse();\nTurnRight();\nRepeat(3, function() {\n  MoveForward();\n});\nTurnLeft();\nWait();\nWait();\nMoveForward();\nMoveForward();\nTurnRight();\nMoveForward();\nUse();\nWait();\nRepeat(3, function() {\n  MoveForward();\n});"
    },
    {
        id: "floor-19",
        name: "Cable Breach",
        introduces: "Shoot()",
        grid: 7,
        start: { x: 3, y: 6, dir: 0 },
        exit: { x: 3, y: 1 },
        chips: [{ x: 3, y: 5 }, { x: 3, y: 3 }, { x: 3, y: 1 }],
        obstacles: [{ x: 1, y: 2 }, { x: 5, y: 2 }],
        switches: [],
        doors: [],
        bridges: [],
        cables: [
            { id: "A", x: 3, y: 5, color: CYAN },
            { id: "B", x: 3, y: 3, color: GREEN }
        ],
        guards: [],
        enemies: [
            { name: "Crawler", x: 3, y: 4, color: RED, stepEvery: 3 },
            { name: "Crawler", x: 0, y: 5, color: RED, stepEvery: 4 },
            { name: "Crawler", x: 6, y: 5, color: RED, stepEvery: 4 }
        ],
        lasers: [],
        requiredPower: [],
        allowed: allow("Repeat", "Use", "Wait", "IfPowerOn", "IfPathClear", "WhilePathClear", "TurnAround", "Shoot"),
        stars: { three: 8, two: 11, one: 15 },
        mission: "Repair both cable nodes while crawlers walk toward Nova.",
        template: "Shoot();\nMoveForward();\nUse();\nMoveForward();\nMoveForward();\nUse();\nMoveForward();\nMoveForward();"
    },
    {
        id: "floor-20",
        name: "Crossfire Repair",
        introduces: "Shoot() + cables",
        grid: 8,
        start: { x: 3, y: 6, dir: 0 },
        exit: { x: 6, y: 1 },
        chips: [{ x: 3, y: 5 }, { x: 5, y: 3 }, { x: 6, y: 1 }],
        obstacles: [{ x: 2, y: 4 }, { x: 6, y: 5 }, { x: 2, y: 2 }],
        switches: [],
        doors: [],
        bridges: [],
        cables: [
            { id: "A", x: 3, y: 5, color: BLUE },
            { id: "B", x: 5, y: 3, color: CYAN }
        ],
        guards: [],
        enemies: [
            { name: "Crawler", x: 3, y: 4, color: RED, stepEvery: 3 },
            { name: "Crawler", x: 5, y: 4, color: RED, stepEvery: 3 },
            { name: "Crawler", x: 0, y: 6, color: RED, stepEvery: 4 },
            { name: "Crawler", x: 7, y: 3, color: RED, stepEvery: 4 }
        ],
        lasers: [],
        requiredPower: [],
        allowed: allow("Repeat", "Use", "Wait", "IfPowerOn", "IfPathClear", "WhilePathClear", "TurnAround", "Shoot"),
        stars: { three: 17, two: 21, one: 27 },
        mission: "Shoot the blockers, repair the cables, and keep moving before the side crawlers close in.",
        template: "Shoot();\nMoveForward();\nUse();\nMoveForward();\nTurnRight();\nShoot();\nMoveForward();\nTurnLeft();\nMoveForward();\nTurnRight();\nShoot();\nMoveForward();\nUse();\nMoveForward();\nTurnLeft();\nMoveForward();\nMoveForward();"
    },
    {
        id: "floor-21",
        name: "Last Stand",
        introduces: "All action",
        grid: 9,
        start: { x: 4, y: 7, dir: 0 },
        exit: { x: 4, y: 1 },
        chips: [{ x: 4, y: 6 }, { x: 4, y: 4 }, { x: 4, y: 2 }, { x: 4, y: 1 }],
        obstacles: [{ x: 2, y: 5 }, { x: 6, y: 5 }, { x: 2, y: 3 }, { x: 6, y: 3 }],
        switches: [],
        doors: [],
        bridges: [],
        cables: [
            { id: "A", x: 4, y: 6, color: BLUE },
            { id: "B", x: 4, y: 4, color: CYAN },
            { id: "C", x: 4, y: 2, color: GREEN }
        ],
        guards: [],
        enemies: [
            { name: "Crawler", x: 4, y: 5, color: RED, stepEvery: 3 },
            { name: "Crawler", x: 4, y: 3, color: RED, stepEvery: 3 },
            { name: "Crawler", x: 0, y: 6, color: RED, stepEvery: 4 },
            { name: "Crawler", x: 8, y: 6, color: RED, stepEvery: 4 },
            { name: "Crawler", x: 0, y: 3, color: RED, stepEvery: 5 },
            { name: "Crawler", x: 8, y: 3, color: RED, stepEvery: 5 }
        ],
        lasers: [],
        requiredPower: [],
        allowed: allow("Repeat", "Use", "Wait", "IfPowerOn", "IfPathClear", "WhilePathClear", "TurnAround", "Shoot"),
        stars: { three: 11, two: 15, one: 22 },
        mission: "A crowd is closing in. Shoot down the lane, repair every cable, then reach the gate.",
        template: "Shoot();\nMoveForward();\nUse();\nMoveForward();\nShoot();\nMoveForward();\nUse();\nMoveForward();\nMoveForward();\nUse();\nMoveForward();"
    }
];

export function getLevel(index) {
    return LEVELS[Math.max(0, Math.min(LEVELS.length - 1, index))];
}
